# Product Approach in Data Analytics, MDS

## HSE, 2024-25

## Course Project. Exploratory Data Analysis

## General Information

__Date of issue:__ 28.04.2025

__Project defense:__ ~ 25.06.2025

## Execution Format

The coursework project is a creative, initiative-based group assignment, carried out by students in teams of 3 to 6 people. At the same time, it should be remembered that the larger the team, the higher the overall requirements for the team and the project they perform. Teams are allowed to be formed from students of different streams.

When evaluating the results of the project carried out by the team, it is mandatory to check and consider the contribution of ***each participant*** to the overall work of the team. Consequently, it is extremely important to responsibly approach the selection of teammates, the distribution of responsibilities within the team, and the prevention of "dead weight" in the team.

If necessary, the team has the right by majority vote to exclude a person from the team *before the project defense* by informing the instructor, in case that person did not contribute during the project and was, in fact, the "dead weight." Remember this possibility, as the presence of "dead weight" can negatively affect the quality and grade of the entire project and, consequently, the entire team!

The registration of team compositions is carried out via the link in the table:

https://docs.google.com/spreadsheets/d/132inC1TqG8xfan65CpmJX_O3jJR5eiDugRWZ-hdMlbc/edit?usp=sharing

## Evaluation and Penalties

The coursework project is evaluated based on the team's oral defense (presentation) of their completed project before a committee. The committee is composed of course instructors, course assistants, and invited industry experts.

Within each defense, the committee assigns two types of grades.

The first grade is for the overall project. It is given by the committee based on the depth of the team's exploration of the subject area, the complexity of the tools used in the project, and other aspects related to the content of the project's terms of reference. When assigning this grade, the committee refers to the criteria detailed below in the "Project Evaluation Criteria" section.

The second grade is the individual grade for each team member. This grade is subsequently recorded in the grade book. The individual grade for a team member is determined by the committee based on how well the member understands the completed project, how they respond to questions addressed personally to them by the committee, how their role in the project is evident, and other aspects related to the person's participation in the team's activities. The individual grade cannot exceed the team's overall project grade (the first grade). However, if the participant confidently and correctly answers all questions addressed to them, is well-versed in the material and content of the completed project, and their role in the team's work is unquestionable, then the individual grade becomes equal to the overall project grade (i.e., in an ideal case, the second grade equals the first grade).

To avoid subjectivity and/or bias in the evaluation by certain committee members towards specific teams, as well as any other manifestations of unequal conditions, the distribution of teams among the committees is done completely randomly using the Numpy library :) — the random seed is the date on which the distribution is performed, for example, `np.random.seed(28042025)`.

To maintain the fairness and impartiality of the random distribution, any transfers of teams between committees (committee changes) are not allowed. Student attendance at the project defense is mandatory; a student's contribution without their presence is not evaluated and automatically equals zero. Additionally, having the camera turned on throughout the entire time in the conference during the project defense is mandatory.

## Task description

<img src="https://pp.userapi.com/c854528/v854528797/c62ce/FiPEibYUxJc.jpg" width="40%">

Over the past 5-10 years, Netflix has gained a large number of viewers. With the increase in viewers, the variety of shows has also increased. Accordingly, analysts in the film industry are faced with the task of researching data with ratings of various series.

In this task, you are to conduct a visual analysis of the dataset **1000 Netflix Shows** (as of 11.06.2017) and draw conclusions.

### Feature description

* `title` - the title of the show.
* `rating` - the show's rating, e.g., G, PG, TV-14, TV-MA.
* `ratingLevel` - description of the rating group and show features.
* `ratingDescription` - the show's rating encoded as a number.
* `release year` - the year the show was released.
* `user rating score` - user score.
* `user rating size` - overall user rating.

### Project requirements

As a result of completing the course project, your team should prepare a presentation and defend it before the committee.

The design of the presentation is entirely up to you, but remember that the result should be relevant for demonstration to a business client — it is most appropriate to perceive the committee evaluating your work in this way. For example, it is not recommended to include lines of code or overuse notebook screenshots in the presentation.

From the perspective of project execution, you need to assume the role of analysts: work on the features, explore the information contained in the dataset, identify trends, patterns, and facts from the data, and, of course, present all of this in a clear manner.

In fact, you can perceive this project in the following way: a business client comes to you — for example, this could be a representative from Netflix who wants to improve certain processes; or a company that wants to produce a new project and/or sell an existing product to Netflix; or a competitor of Netflix interested in a general market study; or any other stakeholder within this industry — and this client asks you to analyze the data and extract useful and significant business insights for them. Of course, the deeper, more meaningful, and more non-trivial these insights are, the more they will pay you :)

### Examples of questions and topics

To prevent you from starting entirely from scratch, we have selected several guiding questions to help you begin your initial analysis.

**Attention:** These questions are only *approximate* and provide just an *initial direction* for your research. While well-developed answers to these questions can bring you a significant amount of initial insights and useful information, you should not base your entire project solely on them. If possible, try to refine and expand on the topics covered in these questions, or even find other layers that are not addressed within them (in fact, there are quite a few!).

So, here are the questions:

- How many rating groups are represented in the data?
- How do the rating groups differ from each other?
- What ratings do users give most frequently?
- What ratings do users give on average?
- In which years were the shows launched?
- Can it be concluded that 2017 was more successful for Netflix than 2016?
- Choose any show (for example, the most liked one) and create its descriptive profile. What questions about it would interest you if you were the client? Answer these questions :)
- What are the features not presented in the data but significantly affecting the existing features?
- How are the ratings formed?
- How was the data collected?

To reiterate: these are just *approximate questions* to provide you with an initial direction to move in. You may choose to answer them or not at your discretion, and act in the way and direction you deem necessary!

### Helpful notes and tips

- Ensure that all charts on the slides can be read even without your comments;
- Avoid making simple text slides;
- Build your analysis based on the goal of presenting useful information for the business;
- Any good Data Scientist should be able to work in a team, so the distribution of your efforts in the project is up to you;
- It's not necessary to limit yourself to the provided dataset. You have the entire internet to find additional information and test your hypotheses. Go for it!

### Approximate EDA Framework

Again, so you don't have to start writing code from scratch, we have built a simple framework of possible steps you might include as the basis of your initial analysis.

As you may have already guessed, we’re not insisting! :)

#### Download the Data
Load the data by executing the code below.

In [ ]:
from google.colab import files
uploaded = files.upload()

Saving NetflixShows.csv to NetflixShows.csv

In [ ]:
import pandas as pd
import numpy as np

In [ ]:
data = pd.read_csv("NetflixShows.csv",encoding="windows-1251",sep=';')
del data['ratingDescription'], data['user rating size']

In [ ]:
data

,title,rating,ratingLevel,release year,user rating score
0,White Chicks,PG-13,"crude and sexual humor, language and some drug...",2004,82.0
1,Lucky Number Slevin,R,"strong violence, sexual content and adult lang...",2006,NaN
2,Grey's Anatomy,TV-14,Parents strongly cautioned. May be unsuitable ...,2016,98.0
3,Prison Break,TV-14,Parents strongly cautioned. May be unsuitable ...,2008,98.0
4,How I Met Your Mother,TV-PG,Parental guidance suggested. May not be suitab...,2014,94.0
...,...,...,...,...,...
995,The BFG,PG,"for action/peril, some scary moments and brief...",2016,97.0
996,The Secret Life of Pets,PG,for action and some rude humor,2016,NaN
997,Precious Puppies,TV-G,Suitable for all ages.,2003,NaN
998,Beary Tales,TV-G,Suitable for all ages.,2013,NaN
999,Growing Up Wild,G,NaN,2016,80.0

In [ ]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 5 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   title              1000 non-null   object
 1   rating             1000 non-null   object
 2   ratingLevel        941 non-null    object
 3   release year       1000 non-null   int64
 4   user rating score  605 non-null    float64
dtypes: float64(1), int64(1), object(3)
memory usage: 39.2+ KB

In [ ]:
n_data = data.fillna(0)
n_data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 5 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   title              1000 non-null   object
 1   rating             1000 non-null   object
 2   ratingLevel        1000 non-null   object
 3   release year       1000 non-null   int64
 4   user rating score  1000 non-null   float64
dtypes: float64(1), int64(1), object(3)
memory usage: 39.2+ KB

In [ ]:
n_data.rename(columns={'user rating score': 'rating_by_users','release year': 'release_year'}, inplace=True)

In [ ]:
n_data

,title,rating,ratingLevel,release_year,rating_by_users
0,White Chicks,PG-13,"crude and sexual humor, language and some drug...",2004,82.0
1,Lucky Number Slevin,R,"strong violence, sexual content and adult lang...",2006,0.0
2,Grey's Anatomy,TV-14,Parents strongly cautioned. May be unsuitable ...,2016,98.0
3,Prison Break,TV-14,Parents strongly cautioned. May be unsuitable ...,2008,98.0
4,How I Met Your Mother,TV-PG,Parental guidance suggested. May not be suitab...,2014,94.0
...,...,...,...,...,...
995,The BFG,PG,"for action/peril, some scary moments and brief...",2016,97.0
996,The Secret Life of Pets,PG,for action and some rude humor,2016,0.0
997,Precious Puppies,TV-G,Suitable for all ages.,2003,0.0
998,Beary Tales,TV-G,Suitable for all ages.,2013,0.0
999,Growing Up Wild,G,0,2016,80.0

#### Remove Duplicates from the Data
- Why did they occur?
- Are there many of them? In which groups are they most prevalent?

In [ ]:
n_data['duplicates'] = n_data.duplicated()
data_new = n_data
data_new.rename(columns={'user rating score': 'rating_by_users'}, inplace=True)

In [ ]:
data_new

,title,rating,ratingLevel,release_year,rating_by_users,duplicates
0,White Chicks,PG-13,"crude and sexual humor, language and some drug...",2004,82.0,False
1,Lucky Number Slevin,R,"strong violence, sexual content and adult lang...",2006,0.0,False
2,Grey's Anatomy,TV-14,Parents strongly cautioned. May be unsuitable ...,2016,98.0,False
3,Prison Break,TV-14,Parents strongly cautioned. May be unsuitable ...,2008,98.0,False
4,How I Met Your Mother,TV-PG,Parental guidance suggested. May not be suitab...,2014,94.0,False
...,...,...,...,...,...,...
995,The BFG,PG,"for action/peril, some scary moments and brief...",2016,97.0,True
996,The Secret Life of Pets,PG,for action and some rude humor,2016,0.0,True
997,Precious Puppies,TV-G,Suitable for all ages.,2003,0.0,False
998,Beary Tales,TV-G,Suitable for all ages.,2013,0.0,False
999,Growing Up Wild,G,0,2016,80.0,True

In [ ]:
data_new.sort_values('rating_by_users', ascending = False)\
     #   .groupby('ratingLevel', as_index = False).agg({'rating' : 'count'})

,title,rating,ratingLevel,release_year,rating_by_users,duplicates
347,13 Reasons Why,TV-MA,For mature audiences. May not be suitable for...,2017,99.0,True
41,13 Reasons Why,TV-MA,For mature audiences. May not be suitable for...,2017,99.0,False
295,13 Reasons Why,TV-MA,For mature audiences. May not be suitable for...,2017,99.0,True
497,13 Reasons Why,TV-MA,For mature audiences. May not be suitable for...,2017,99.0,True
241,13 Reasons Why,TV-MA,For mature audiences. May not be suitable for...,2017,99.0,True
...,...,...,...,...,...,...
668,Beverly Hills Chihuahua 3: Viva La Fiesta!,G,General Audiences. Suitable for all ages.,2012,0.0,False
693,Home: Adventures with Tip & Oh,TV-Y7,Suitable for children ages 7 and older,2017,0.0,True
690,Word Party,TV-Y,Suitable for all ages.,2016,0.0,False
128,Chelsea,TV-MA,For mature audiences. May not be suitable for...,2017,0.0,False
647,Angry Birds,TV-G,Suitable for all ages.,2013,0.0,True

In [ ]:
data_new.rating_by_users.describe()

count    1000.000000
mean       50.877000
std        42.235242
min         0.000000
25%         0.000000
50%        70.000000
75%        91.000000
max        99.000000
Name: rating_by_users, dtype: float64

In [ ]:
data_new_dub_only = data_new.query('duplicates == True')
data_new_dub_only.shape

(500, 6)

In [ ]:
data_new_dub_only.sort_values('rating_by_users', ascending = False)

,title,rating,ratingLevel,release_year,rating_by_users,duplicates
141,13 Reasons Why,TV-MA,For mature audiences. May not be suitable for...,2017,99.0,True
241,13 Reasons Why,TV-MA,For mature audiences. May not be suitable for...,2017,99.0,True
189,13 Reasons Why,TV-MA,For mature audiences. May not be suitable for...,2017,99.0,True
497,13 Reasons Why,TV-MA,For mature audiences. May not be suitable for...,2017,99.0,True
295,13 Reasons Why,TV-MA,For mature audiences. May not be suitable for...,2017,99.0,True
...,...,...,...,...,...,...
915,Back to the Secret Garden,G,General Audiences. Suitable for all ages.,2002,0.0,True
913,Balto 2: Wolf Quest,G,General Audiences. Suitable for all ages.,2001,0.0,True
909,Pooh's Grand Adventure: The Search for Christo...,G,General Audiences. Suitable for all ages.,1997,0.0,True
906,Fantasia 2000,G,General Audiences. Suitable for all ages.,2000,0.0,True
904,Babe: Pig in the City,G,General Audiences. Suitable for all ages.,1998,0.0,True

In [ ]:
data_new_dub_only.rating_by_users.describe()

count    500.00000
mean      60.07800
std       40.74231
min        0.00000
25%        0.00000
50%       81.00000
75%       94.00000
max       99.00000
Name: rating_by_users, dtype: float64

Ищем дубликаты **Текст, выделенный полужирным шрифтом**

In [ ]:
data_new_dub_only = data_new.query('duplicates == True')
data_new_dub_only['ratingLevel'].str.split('.').str[0]
data_new_dub_only_title = data_new_dub_only['ratingLevel'].str.split('.').str[0]

In [ ]:
data_new_dub_only

,title,rating,ratingLevel,release_year,rating_by_users,duplicates
50,Lucky Number Slevin,R,"strong violence, sexual content and adult lang...",2006,0.0,True
52,Grey's Anatomy,TV-14,Parents strongly cautioned. May be unsuitable ...,2016,98.0,True
53,Prison Break,TV-14,Parents strongly cautioned. May be unsuitable ...,2008,98.0,True
56,How I Met Your Mother,TV-PG,Parental guidance suggested. May not be suitab...,2014,94.0,True
57,Supernatural,TV-14,Parents strongly cautioned. May be unsuitable ...,2016,95.0,True
...,...,...,...,...,...,...
991,Dawn of the Croods,TV-Y7,Suitable for children ages 7 and older,2017,72.0,True
992,Alpha and Omega: Dino Digs,TV-G,Suitable for all ages.,2016,0.0,True
995,The BFG,PG,"for action/peril, some scary moments and brief...",2016,97.0,True
996,The Secret Life of Pets,PG,for action and some rude humor,2016,0.0,True
999,Growing Up Wild,G,0,2016,80.0,True

In [ ]:
data_new_dub_only = data_new.query('duplicates == True')
data_new_dub_only.groupby('ratingLevel', as_index = False).agg({'title' : 'count'}).sort_values('title', ascending = False)

                                          ratingLevel  title
6   Parents strongly cautioned. May be unsuitable ...    124
3           General Audiences. Suitable for all ages.     82
7                              Suitable for all ages.     55
1   For mature audiences.  May not be suitable for...     50
0                                                   0     26
4   Parental guidance suggested. May not be suitab...     23
9   Suitable for children ages 7 and older.  Conte...     19
8              Suitable for children ages 7 and older     15
5   Parental guidance suggested. May not be suitab...      9
19                     for action and some rude humor      5
17                   fantasy action and mild language      5
10                     This movie has not been rated.      4
31                             mild thematic elements      4
44    some rude humor, language and some scary action      4
50      some thematic elements, rude humor and action      4
33         moderate adult language and intense action      4
22                          for rude humor and action      3
23       for some sequences of scary action and peril      3
32                mild thematic material and language      3
56  thematic elements, scary images, some language...      3
46           some scary images, action and rude humor      3
18             fantasy action/peril and some language      3
28                    mild action and some rude humor      2
13                     adult content and mld violence      2
15  animated action violence, some scary cartoon i...      2
47  some scary images, perilous action sequences a...      2
54  strong violence, sexual content and adult lang...      2
42                                 some rude dialogue      2
48                                 some scary moments      2
30                              mild suggestive humor      2
29                                 mild sci-fi action      2
34         rude and suggestive humor, and some action      2
27                         mild action and rude humor      2
39                 slapstick action and mild language      2
38                   sequences of martial arts action      2
35                         rude humor and some action      2
16                                     fantasy action      1
12  action violence throughout, some scary images,...      1
11                              action and rude humor      1
14                            animal action and humor      1
2   For some rude and suggestive material, and for...      1
24         intense scenes dealing with strong content      1
21  for action/peril, some scary moments and brief...      1
20               for action, peril and brief language      1
40  some action violence involving gunplay, and mi...      1
25               language and some crude sexual humor      1
37  sci-fi action violence throughout, brief langu...      1
36  scary images, suggestive material, some langua...      1
26       martial arts action and some mild rude humor      1
45                                  some scary images      1
43                                    some rude humor      1
41                                         some peril      1
49                               some sexual material      1
52  strong crude sexual content, pervasive languag...      1
51                 some violence and one sexual scene      1
53            strong violence and language throughout      1
55  thematic elements, scary images, action and peril      1

In [ ]:
split_columns = data_new_dub_only['ratingLevel'].str.split('.', expand=True).replace('', np.nan).replace(' ', np.nan).fillna('No comment')
split_columns.columns = [f'comment_part_{i+1}' for i in range(split_columns.shape[1])]




#.replace('', np.nan).replace(' ', np.nan).fillna('No comment')

<ipython-input-20-41874a996b82>:1: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  split_columns = data_new_dub_only['ratingLevel'].str.split('.', expand=True).replace('', np.nan).replace(' ', np.nan).fillna('No comment')

In [ ]:
split_columns.rename(columns={'comment_part_1': 'first_category'}, inplace=True)

In [ ]:
split_columns

,first_category,comment_part_2,comment_part_3
50,"strong violence, sexual content and adult lang...",No comment,No comment
52,Parents strongly cautioned,May be unsuitable for children ages 14 and under,No comment
53,Parents strongly cautioned,May be unsuitable for children ages 14 and under,No comment
56,Parental guidance suggested,May not be suitable for all children,No comment
57,Parents strongly cautioned,May be unsuitable for children ages 14 and under,No comment
...,...,...,...
991,Suitable for children ages 7 and older,No comment,No comment
992,Suitable for all ages,No comment,No comment
995,"for action/peril, some scary moments and brief...",No comment,No comment
996,for action and some rude humor,No comment,No comment
999,No comment,No comment,No comment

In [ ]:
split_columns.groupby('comment_part_2', as_index = False).agg({'first_category' : 'count'}).sort_values('first_category', ascending = False)

                                      comment_part_2  first_category
6                                         No comment             193
2   May be unsuitable for children ages 14 and under             124
5                              Suitable for all ages              82
1      May not be suitable for children 17 and under              50
3               May not be suitable for all children              23
0                  Content contains fantasy violence              19
4                   May not be suitable for children               9

In [ ]:
split_columns

,first_category,comment_part_2,comment_part_3
50,"strong violence, sexual content and adult lang...",No comment,No comment
52,Parents strongly cautioned,May be unsuitable for children ages 14 and under,No comment
53,Parents strongly cautioned,May be unsuitable for children ages 14 and under,No comment
56,Parental guidance suggested,May not be suitable for all children,No comment
57,Parents strongly cautioned,May be unsuitable for children ages 14 and under,No comment
...,...,...,...
991,Suitable for children ages 7 and older,No comment,No comment
992,Suitable for all ages,No comment,No comment
995,"for action/peril, some scary moments and brief...",No comment,No comment
996,for action and some rude humor,No comment,No comment
999,No comment,No comment,No comment

In [ ]:
df['comments'] = df['comments'].replace('', np.nan).replace(' ', np.nan)

NameError: name 'df' is not defined

In [ ]:
for_text = data_new.ratingLevel
for_text
df_unique = for_text.drop_duplicates().shape
df_unique

(100,)

In [ ]:
for_text.sort_values().unique()

TypeError: '<' not supported between instances of 'int' and 'str'

In [ ]:
data_new_dub_only_title

50     strong violence, sexual content and adult lang...
52                            Parents strongly cautioned
53                            Parents strongly cautioned
56                           Parental guidance suggested
57                            Parents strongly cautioned
                             ...
991               Suitable for children ages 7 and older
992                                Suitable for all ages
995    for action/peril, some scary moments and brief...
996                       for action and some rude humor
999                                                  NaN
Name: ratingLevel, Length: 366, dtype: object

In [ ]:
data_new_dub_only_title.sort_values().unique()

array(['For mature audiences',
       'For some rude and suggestive material, and for language',
       'General Audiences', 'Parental guidance suggested',
       'Parents strongly cautioned', 'Suitable for all ages',
       'Suitable for children ages 7 and older',
       'This movie has not been rated', 'action and rude humor',
       'action violence throughout, some scary images, and language',
       'adult content and mld violence', 'animal action and humor',
       'animated action violence, some scary cartoon images and mild language',
       'fantasy action', 'fantasy action and mild language',
       'fantasy action/peril and some language',
       'for action and some rude humor',
       'for action, peril and brief language',
       'for action/peril, some scary moments and brief rude humor',
       'for rude humor and action',
       'for some sequences of scary action and peril',
       'intense scenes dealing with strong content',
       'language and some crude sexual humor',
       'martial arts action and some mild rude humor',
       'mild action and rude humor', 'mild action and some rude humor',
       'mild sci-fi action', 'mild suggestive humor',
       'mild thematic elements', 'mild thematic material and language',
       'moderate adult language and intense action',
       'rude and suggestive humor, and some action',
       'rude humor and some action',
       'scary images, suggestive material, some language and smoking',
       'sci-fi action violence throughout, brief language and momentary smoking',
       'sequences of martial arts action',
       'slapstick action and mild language',
       'some action violence involving gunplay, and mild rude humor',
       'some peril', 'some rude dialogue', 'some rude humor',
       'some rude humor, language and some scary action',
       'some scary images', 'some scary images, action and rude humor',
       'some scary images, perilous action sequences and mild rude humor',
       'some scary moments', 'some sexual material',
       'some thematic elements, rude humor and action',
       'some violence and one sexual scene',
       'strong crude sexual content, pervasive language, and drug use',
       'strong violence and language throughout',
       'strong violence, sexual content and adult language',
       'thematic elements, scary images, action and peril',
       'thematic elements, scary images, some language and suggestive humor',
       nan], dtype=object)

In [ ]:
data_without_dublic = data.drop_duplicates()
data_without_dublic

,title,rating,ratingLevel,release year,user rating score
0,White Chicks,PG-13,"crude and sexual humor, language and some drug...",2004,82.0
1,Lucky Number Slevin,R,"strong violence, sexual content and adult lang...",2006,NaN
2,Grey's Anatomy,TV-14,Parents strongly cautioned. May be unsuitable ...,2016,98.0
3,Prison Break,TV-14,Parents strongly cautioned. May be unsuitable ...,2008,98.0
4,How I Met Your Mother,TV-PG,Parental guidance suggested. May not be suitab...,2014,94.0
...,...,...,...,...,...
989,Russell Madness,PG,some rude humor and sports action,2015,NaN
993,Wiener Dog Internationals,G,General Audiences. Suitable for all ages.,2015,NaN
994,Pup Star,G,General Audiences. Suitable for all ages.,2016,NaN
997,Precious Puppies,TV-G,Suitable for all ages.,2003,NaN
998,Beary Tales,TV-G,Suitable for all ages.,2013,NaN

#### How many rating groups are represented in the data?

In [ ]:
...

#### What ratings do users give more frequently?

- Create a histogram of the ratings.
- Why are these ratings given most often?

In [ ]:
...

#### Display the Main Information About User Ratings
- What are the mean, standard deviation, minimum, maximum, and median?
- Do the median and mean differ?
- Can these characteristics differ significantly? Why?

In [ ]:
...

#### In which years were the shows in the dataset launched?

In [ ]:
...

#### Create a Chart Showing the Distribution of the Number of Shows Launched by Year

- Is there growth observed?
- Are there any outliers?
- What do the outliers represent?
- What might have caused them?

In [ ]:
...

#### Compare the Average User Rating in 2016 with the Average Rating in 2017
- Can it be concluded that 2017 was more successful for Netflix? ("More successful" means users gave higher ratings on average)
- How else can "success" be evaluated?

In [ ]:
...

#### How Can the Distribution of Users Across Rating Groups Be Shown More Clearly?

Below are two charts showing the distribution of shows by rating groups. Which type of chart is more visually interpretable?

Create the chart you consider more interpretable. Draw a conclusion.

Are there any other, more advanced visualizations that could be used?

![Charts](https://pp.userapi.com/c852024/v852024281/1a53b1/jSOsBIhxK3U.jpg)

In [ ]:
...

#### Now You Need to Choose Any of the Presented Shows and Use the Tools You Have Studied to Create a Descriptive Profile of This Show :)

Analysts and Data Scientists love to compare everything, so when creating the descriptive profile, we recommend comparing the selected show with others based on certain characteristics.

In [ ]:
...

## Project Evaluation Criteria

The grade for the group project as a whole — the first of the two grades — is given on a 10-point scale based on 5 criteria. Additionally, the committee may, at its discretion, add (but not decrease) a certain number of bonus points beyond these criteria.

Each of the criteria will be listed and reviewed below.

### Criterion 1: Technical Informativeness – It is necessary to identify non-trivial dependencies and trends in the data (up to 2 points)

This criterion evaluates how technically advanced you have become in identifying patterns, trends, and dependencies in the data. The more complex tools you apply during the project and the more complex and non-trivial dependencies you uncover, the higher your team's score will be for this criterion!

### Criterion 2: Analytical Informativeness – It is necessary to interpret the data and draw conclusions useful for the business (up to 2 points)

This criterion evaluates the practical significance of your actions, the interpretation of technical tools, the ability to highlight the usefulness and importance of the conclusions from a business perspective, and the ability to align the results with the original business goals and "sell" what you have accomplished.

### Criterion 3: Visualization – The technical execution of the charts is evaluated (up to 2 points)

This criterion assesses the complexity and technicality of your visualizations. Visualizations should be clear, aesthetically pleasing, understandable, easily interpretable, and non-trivial in terms of technical execution and the conclusions they convey.

*The maximum score for this criterion (**2 points**) cannot be achieved if only basic visualization libraries such as Matplotlib and Seaborn are used.*

### Criterion 4: Dataset Preprocessing – Data Cleaning/Replacement (up to 1 point)

This criterion evaluates the completeness of all actions performed in terms of data preparation and initial dataset preprocessing.

### Criterion 5: Data Enrichment – Adding New Features/Datasets (up to 3 points)

This criterion evaluates the extent to which feature engineering is used based on existing data, as well as data enrichment by supplementing the existing dataset with meaningful information from related external datasets, various external resources, and other sources. Note that related external information should not replace or substitute the original task and data in the presented dataset, but should only complement and enrich it. The correctness and depth of interaction with external resources are evaluated within this criterion!

*The maximum score for this criterion (**3 points**) can only be achieved with correct and meaningful work involving at least two sources of external data (two external datasets), as well as having at least two examples of valid and meaningful application of feature engineering.*

*For this criterion, **2 points** can only be achieved with correct and meaningful work involving at least one source of external data (an external dataset), as well as having at least one example of valid and meaningful application of feature engineering.*